@startuml
title Monitor - Disparo temporal de transición (según diagrama)

participant Monitor
participant PetriNet
participant EnableVector
participant TimeRangeMatrix
participant StateEquationUtils
participant PetriNetAnalyzer
participant CurrentMarking


' ===== !isTokenEnable CONTROL ======='
activate Monitor
Monitor -> PetriNet: fire (int transitionIndex)
deactivate Monitor
activate PetriNet

PetriNet -> EnableVector: isTransitionEnabled int transitionIndex)
|||
activate EnableVector

EnableVector -> EnableVector: tokenEnabledTransition [int transitionIndex] : true

|||
EnableVector -> EnableVector: currentTime : System.nanoTime()
|||
EnableVector -> TimeRangeMatrix: isInsideTimeRange (int transition, long enabledTime, long currentTime)
activate TimeRangeMatrix
TimeRangeMatrix --> EnableVector: true
deactivate TimeRangeMatrix

|||
EnableVector -> EnableVector: isThereThreadWaitingForTransition (int transitionIndex) : false
EnableVector -> PetriNet: true
deactivate EnableVector

' ===== calculateStateEquation ========='
|||
PetriNet -> StateEquationUtils: calculateStateEquation (int transitionIndex, IncidenceMatrix im, CurrentMarking cm)
activate StateEquationUtils
StateEquationUtils --> PetriNet: nextMarking
|||
deactivate StateEquationUtils

PetriNet -> CurrentMarking: setMarking(int[] nextMarking)
activate CurrentMarking
deactivate CurrentMarking
|||

PetriNet -> PetriNetAnalyzer: checkPlaceInvariants (int[] marking)
activate PetriNetAnalyzer
deactivate PetriNetAnalyzer


' ==== isThereThrearWaitingForTrasition CONTROL ====
|||
PetriNet -> EnableVector: isThereThreadWaitingForTransition (int transition)
activate EnableVector
EnableVector --> PetriNet: false
deactivate EnableVector
|||
PetriNet -> EnableVector: updateEnableVector(IncidenceMatrix incidenceMatrix, CurrentMarking currentMarking)
activate EnableVector
deactivate EnableVector
PetriNet --> Monitor: true
deactivate PetriNet

@enduml
